name: Main
on:
  workflow_dispatch:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.9"

      - name: Upgrade pip, setuptools, and wheel
        run: python -m pip install --upgrade pip setuptools wheel

      - name: Install Deps
        run: |
          pip install --upgrade pylint
          pip install --upgrade mypy
          pip install --upgrade -r requirements.txt

      - name: Run Linter
        run: pylint ./statsig_ai --rcfile .pylintrc

      - name: Run Type Checker
        run: |
          mypy ./statsig_ai --check-untyped-defs

  test:
    needs: lint
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.9"

      - name: Upgrade pip, setuptools, and wheel
        run: python -m pip install --upgrade pip setuptools wheel

      - name: Install Deps
        run: |
          pip install --upgrade -r requirements.txt
          pip install --upgrade .[test]

      - name: Run Tests
        run: pytest -q
        env:
          test_api_key: ${{ secrets.SDK_CONSISTENCY_TEST_COMPANY_API_KEY }}
          test_client_key: ${{ secrets.KONG_CLIENT_SDK_KEY }}
